name: Pull Request Testing

on:
  pull_request:
    branches: [main]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Graphviz
      run: |
        sudo apt-get install graphviz graphviz-dev
        pip install pygraphviz
    
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test with pytest
      run: |
        python -m pytest -o log_cli=true -s -vv --cov
    needs: dependencies

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Black Formatter
      run: |
        python -m black .
    needs: dependencies